export const games = [
  {
    id: 1,
    title: "Minecraft",
    genre: "Sandbox",
    rating: 5,
    img: "⛏️",
    description: "Будуй що завгодно в безмежному світі з блоків.",
    platform: "PC, Mobile, Console",
    year: 2011,
  },
  {
    id: 2,
    title: "Valorant",
    genre: "Shooter",
    rating: 4,
    img: "🎯",
    description: "Тактичний шутер від Riot Games з унікальними агентами.",
    platform: "PC",
    year: 2020,
  },
  {
    id: 3,
    title: "FIFA 25",
    genre: "Sports",
    rating: 3,
    img: "⚽",
    description: "Найпопулярніший футбольний симулятор у світі.",
    platform: "PC, Console",
    year: 2024,
  },
  {
    id: 4,
    title: "Cyberpunk 2077",
    genre: "RPG",
    rating: 5,
    img: "🤖",
    description: "Відкритий світ майбутнього від CD Projekt Red.",
    platform: "PC, Console",
    year: 2020,
  },
  {
    id: 5,
    title: "Hollow Knight",
    genre: "Indie",
    rating: 5,
    img: "🦋",
    description: "Атмосферний метроідванія про підземне королівство.",
    platform: "PC, Console",
    year: 2017,
  },
  {
    id: 6,
    title: "Rocket League",
    genre: "Sports",
    rating: 4,
    img: "🚀",
    description: "Футбол на машинах — звучить безглуздо, грається геніально.",
    platform: "PC, Console",
    year: 2015,
  },
];
